service: aws-node-puppeteer
provider:
  name: aws
   
  ##profile: <AWSLambdaFullAccess> 
  runtime: nodejs12.x
#stage: dev
#region: us-east-1
#role: arn:aws:iam::499870337613:role/serverless
  
plugins:
  - serverless-offline
  - serverless-plugin-chrome
  
package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**

functions:
  serverless:
    handler: handler.Canary
    #memorySize: 1536MB
    #timeout: 30
    #events:
     # - http:
      #    path: /
       #   method: get

          

