service: aws-node-puppeteer
provider:
  name: aws
   
  runtime: nodejs12.x

  
plugins:
  - serverless-offline
  - serverless-plugin-chrome
  
package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**

functions:
  serverless:
    handler: handler.Canary
    

